GET http://127.0.0.1:5000/
Accept: text/html

###
GET http://15.165.67.32:5000/result/태블릿

###
GET http://15.165.67.32:5000/search?item=태블릿

###
GET http://127.0.0.1:5000/search?item=태블릿

###
GET http://127.0.0.1:5000/search?item=세제

###
GET http://127.0.0.1:5000/search?item=신발

###
GET http://127.0.0.1:5000/search?item=바지

###
GET http://127.0.0.1:5000/search?item=신라면

###
GET http://127.0.0.1:5000/search?item=농심신라면

###
GET http://127.0.0.1:5000/product?no=3054694